name: integration
on: 
  workflow_run:
    workflows: ["main"]
    types:
      - completed
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: run integration tests
        run: node dist/integrationTest.js