name: main
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: '24'
      - name: run tests
        run: node dist/userValidationTest.js