name: Workflow 1

on:
  push:
    branches:
      - main
      - master

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Workflow 1
        run: echo "Workflow 1 completed"
