name: Workflow 4

on:
  workflow_run:
    workflows: ["Workflow 3"]
    types:
      - completed

jobs:
  job4:
    runs-on: ubuntu-latest
    steps:
      - name: Print Workflow 4
        run: echo "workflow 4"
